version: "3"
services:
  www:
    container_name: www
    build: .
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./application/:/var/www/html
    networks:
      - default
volumes:
  persistent:
